# To expose Spring Boot info actuator
spring:
  application:
    name: springboot_health
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
info:
  application:
    name: ${spring.application.name}
    description: Application for testing CI/CD pipeline
    version: 06.15.22
